

CREATE TABLE USER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(500),
    ADDRESS VARCHAR(500),
    PHONE_NUMBER VARCHAR(20),
    GENDER VARCHAR(20),
    DATE_OF_BIRTH VARCHAR(20),
    POINT INTEGER,
    PASSWORD VARCHAR(500),
    ROLE VARCHAR(30)
);

INSERT INTO USER(ID, NAME, ADDRESS, PHONE_NUMBER, GENDER, DATE_OF_BIRTH, POINT, PASSWORD, ROLE)
VALUES (NULL, 'PHUC HOANG', '3/2 STREET', '0909090909', 'MALE', '02/02/2002', 0, '123', 'USER');

CREATE TABLE BRAND(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(500)
);

CREATE TABLE CATEGORY(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(500)
);

CREATE TABLE PRODUCT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(500),
    DESCRIPTION TEXT,
    PRICE DOUBLE,
    CATEGORY INTEGER,
    PICTURE TEXT,
    BRAND INTEGER,
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(ID),
    FOREIGN KEY (BRAND) REFERENCES BRAND(ID)
);

CREATE TABLE IN_CART(
    USERID INTEGER,
    PRODUCT_ID INTEGER,
    FOREIGN KEY (USERID) REFERENCES USER(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE BUY_HISTORY(
    USERID INTEGER,
    PRODUCT_ID INTEGER,
    DATE_BUY VARCHAR(50),
    FOREIGN KEY (USERID) REFERENCES USER(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);
